// 389. Find the Difference

// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.


// Input: s = "", t = "y"
// Output: "y"


// Input: s = "a", t = "aa"
// Output: "a"



class Solution {
    public char findTheDifference(String s, String t) {
        int sSum = 0;
        for(int i=0;i<s.length();i++) {
            sSum += t.charAt(i) - s.charAt(i);
        }
        sSum += t.charAt(t.length() - 1);
        return (char)sSum;
    }
}